name: Qlient HTTP Requests - Publish

on:
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13
      - name: Install dependencies
        run: poetry install
      - name: Publish
        run: poetry publish --build --username "${{secrets.PYPI_USERNAME}}" --password "${{secrets.PYPI_PASSWORD}}" --no-interaction